version: '3.1'

services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./db_data:/data/db

  dashboard:
    image: parseplatform/parse-dashboard:5.0.0
    ports:
      - 4040:4040
    environment:
      PARSE_DASHBOARD_SERVER_URL: ${SERVER_URL}
      PARSE_DASHBOARD_APP_ID: ${APP_ID}
      PARSE_DASHBOARD_MASTER_KEY: ${MASTER_KEY}
      PARSE_DASHBOARD_APP_NAME: ${APP_NAME}
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
      PARSE_DASHBOARD_USER_ID: ${DASH_USER}
      PARSE_DASHBOARD_USER_PASSWORD: ${DASH_PASS}

